
spring.r2dbc:
  username: postgres
  password: root
  url: r2dbc:postgresql://localhost:5432/postgres
  repositories.enabled: true

  pool:
    enabled: true
    initial-size: 10
    max-idle-time: 1m
    max-size: 30

server:
  port: 9081

app:
  cache:
    size: 365
  rest:
    api:
      prefix: /api




